apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: kdhqncmna-go 
  janus-idp.io/tekton: kdhqncmna-go
  backstage.io/kubernetes-id: kdhqncmna-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kdhqncmna-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  